<?xml version="1.0"?>
<package format="3">
  <name>evo_vision</name>
  <version>0.1.0</version>
  <description>Evo-Botics camera perception for QR scanning, depth obstacle scan, and future object detection.</description>
  <maintainer email="evobotics@example.com">Evo-Botics</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-pyzbar</exec_depend>
  <exec_depend>libzbar0</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
