#!/usr/bin/env bash
# Shared robot script configuration.
# Precedence: environment variable > config.local.sh > defaults below.
#
# Persist the DHCP robot IP with: ./scripts/robot.sh config ip <ip>
# Override once with: JETSON_IP=<ip> ./scripts/robot.sh status

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

[ -f "${SCRIPT_DIR}/config.local.sh" ] && . "${SCRIPT_DIR}/config.local.sh"

: "${JETSON_IP:=}"
: "${JETSON_USER:=jetson}"
: "${SSH_CONTROL_PERSIST_SEC:=300}"
: "${SSH_SERVER_ALIVE_INTERVAL_SEC:=15}"
: "${SSH_SERVER_ALIVE_COUNT_MAX:=4}"
: "${CONTAINER:=evo-ros}"
: "${AGENT_CONTAINER:=evo-micro-ros-agent}"
: "${MICRO_ROS_SERVICE:=evo-micro-ros-agent.service}"
: "${MICRO_ROS_SERIAL_DEVICE:=/dev/myserial}"
: "${ROS_DOMAIN_ID:=30}"
: "${HOST_WS:=/home/${JETSON_USER}/evo_ws}"
: "${DOCKER_WS:=/root/evo_ws}"
: "${DOCKER_MAP_DIR:=/root/maps}"
: "${HOST_MAP_DIR:=/home/${JETSON_USER}/maps}"
: "${DEFAULT_MAP_NAME:=school_v1}"
: "${CAMERA_PORT:=8080}"
: "${CAMERA_TOPIC:=/camera/color/image_raw}"
: "${DEPTH_TOPIC:=/camera/depth/image_raw}"
: "${PACKAGED_MAP_PATH:=${DOCKER_WS}/src/evo_navigation/maps/${DEFAULT_MAP_NAME}.yaml}"
: "${MAP_PATH:=${PACKAGED_MAP_PATH}}"
: "${FASTDDS_BUILTIN_TRANSPORTS:=UDPv4}"
: "${RMW_IMPLEMENTATION:=rmw_fastrtps_cpp}"
: "${WEB_STARTUP_TIMEOUT:=120}"
: "${CAMERA_STARTUP_TIMEOUT_SEC:=45}"
: "${CAMERA_MAX_FPS:=8.0}"
: "${CAMERA_MAX_WIDTH:=640}"
: "${CAMERA_JPEG_QUALITY:=60}"
: "${PERSON_DETECTION_ENABLED:=false}"
: "${PERSON_DETECTION_MODEL_PATH:=/root/models/person_detector.onnx}"
: "${PERSON_DETECTION_CONFIDENCE:=0.55}"
: "${PERSON_DETECTION_NMS:=0.45}"
: "${PERSON_DETECTION_MAX_FPS:=5.0}"
: "${APPROACH_MIN_CONFIDENCE:=0.65}"
: "${APPROACH_MIN_DISTANCE_M:=0.5}"
: "${APPROACH_MAX_DISTANCE_M:=2.5}"
: "${APPROACH_ZONE_MIN_X:=0.25}"
: "${APPROACH_ZONE_MAX_X:=0.75}"
: "${APPROACH_ZONE_MIN_Y:=0.15}"
: "${APPROACH_ZONE_MAX_Y:=0.95}"
: "${APPROACH_DEBOUNCE_FRAMES:=3}"
: "${APPROACH_COOLDOWN_SEC:=10.0}"
# Person detection can intermittently miss a stationary visitor. Keep presence
# latched long enough for the visitor to say "Hi" before declaring departure.
: "${APPROACH_ABSENCE_RESET_SEC:=10.0}"
: "${PRESENCE_GREETING_FALLBACK_SEC:=5.0}"
: "${INTENT_TIMEOUT_SEC:=45.0}"
: "${QR_INACTIVITY_TIMEOUT_SEC:=20.0}"
: "${RECEPTION_ALLOWED_DESTINATION_IDS:=1,2}"
: "${SCHOOL_RECEPTION_WAYPOINT_CONFIG_PATH:=${DOCKER_WS}/install/evo_navigation/share/evo_navigation/config/school_reception_waypoints.yaml}"
: "${RECEPTION_WAYPOINT_CONFIG_PATH:=${SCHOOL_RECEPTION_WAYPOINT_CONFIG_PATH}}"
: "${DEFAULT_DEMO_MAP:=school}"
: "${HOME_RECEPTION_WAYPOINT_CONFIG_PATH:=}"
: "${DEMO_CLEAN_START:=true}"
: "${DEMO_START_LARAVEL:=false}"
: "${DEMO_BACKEND_START_TIMEOUT_SEC:=60}"
: "${HOME_MAP_PATH:=}"
: "${SCHOOL_MAP_PATH:=${PACKAGED_MAP_PATH}}"
: "${REAL_NAVIGATION_TIMEOUT_SEC:=120.0}"
: "${REAL_LOCALIZATION_TIMEOUT_SEC:=0.0}"
: "${REAL_MAX_LOCALIZATION_XY_VARIANCE:=0.5}"
: "${REAL_AUTOMATIC_RETURN_ENABLED:=false}"
: "${INITIAL_POSE_AUTO_ENABLED:=true}"
: "${AUTOMATIC_RETURN_ENABLED:=true}"
: "${ROSBRIDGE:=true}"
: "${ROSBRIDGE_PORT:=9090}"
: "${ARM_INPUT_TOPIC:=/evo/arm/command}"
: "${ARM_OUTPUT_TOPIC:=/arm6_joints}"
: "${APP_SCHEME:=http}"
: "${APP_HOST:=}"
: "${APP_PORT:=8000}"
: "${KIOSK_PATH:=/kiosk?scan=robot}"
: "${RECEPTION_VALIDATION_PATH:=/api/reservations/validate}"
: "${RECEPTION_VALIDATION_URL:=}"
: "${PIPER_MODEL_PATH:=}"
: "${AUDIO_OUTPUT_DEVICE:=}"
: "${STT_MODEL_PATH:=}"
: "${STT_DEVICE:=cpu}"
: "${STT_COMPUTE_TYPE:=int8}"
: "${VOICE_LANGUAGE:=en}"
: "${MICROPHONE_DEVICE:=-1}"
: "${STT_PHRASE_TIME_LIMIT_SEC:=5.0}"
: "${STT_PAUSE_THRESHOLD_SEC:=0.4}"
: "${STT_NON_SPEAKING_DURATION_SEC:=0.2}"
: "${VOICE_STARTUP_TIMEOUT_SEC:=45}"
: "${WEBRTC_MIC_ENABLED:=false}"
: "${WEBRTC_MIC_SOURCE_MASTER:=}"
: "${WEBRTC_MIC_SOURCE_NAME:=evo_webrtc_mic}"
: "${WEBRTC_MIC_SOURCE_VOLUME:=75%}"
: "${KIOSK_URL:=}"
: "${KIOSK_DISPLAY:=:0}"
: "${KIOSK_SESSION:=evo_kiosk}"
: "${FOXGLOVE_PORT:=8765}"
: "${FOXGLOVE_SESSION:=evo_foxglove}"
: "${MCU_PROBE_TOPIC:=/battery}"
: "${SLAM_USE_COLLISION_MONITOR:=false}"
: "${NAV_USE_COLLISION_MONITOR:=false}"
: "${SERVICE_LOG_DIR:=/home/${JETSON_USER}/evo_logs}"
